### ISSUE TITLE
MySQL database support

### ISSUE THREAD

**Issue by ghost** [mbarakaja/saraki#29]
Hi @mbarakaja ,

Hope you are all well !

I have several questions about your **saraki** project :-)

So, I forked it in order to dockerize it, and made PR https://github.com/mbarakaja/saraki/pull/27, with mysql and postgresql as a datastore. 

But, It triggers the following error with the mysql dsn:
```sh
saraki-server | Traceback (most recent call last):
saraki-server |   File "/opt/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
saraki-server |     self.dialect.do_execute(
saraki-server |   File "/opt/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
saraki-server |     cursor.execute(statement, parameters)
saraki-server |   File "/opt/venv/lib/python3.8/site-packages/mysql/connector/cursor.py", line 551, in execute
saraki-server |     self._handle_result(self._connection.cmd_query(stmt))
saraki-server |   File "/opt/venv/lib/python3.8/site-packages/mysql/connector/connection.py", line 490, in cmd_query
saraki-server |     result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
saraki-server |   File "/opt/venv/lib/python3.8/site-packages/mysql/connector/connection.py", line 395, in _handle_result
saraki-server |     raise errors.get_exception(packet)
saraki-server | mysql.connector.errors.ProgrammingError: 1067 (42000): Invalid default value for 'is_owner'
saraki-server |
saraki-server | The above exception was the direct cause of the following exception:
saraki-server |
saraki-server | Traceback (most recent call last):
saraki-server |   File "app.py", line 37, in <module>
saraki-server |     database.create_all()
saraki-server |   File "/opt/venv/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 1039, in create_all
saraki-server |     self._execute_for_all_tables(app, bind, 'create_all')
saraki-server |   File "/opt/venv/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 1031, in _execute_for_all_tables
saraki-server |     op(bind=self.get_engine(app, bind), **extra)
saraki-server |   File "/opt/venv/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 4553, in create_all
saraki-server |     bind._run_visitor(
saraki-server |   File "/opt/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2095, in _run_visitor
saraki-server |     conn._run_visitor(visitorcallable, element, **kwargs)
saraki-server |   File "/opt/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1656, in _run_visitor
saraki-server |     visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
saraki-server |   File "/opt/venv/lib/python3.8/site-packages/sqlalchemy/sql/visitors.py", line 145, in traverse_single
saraki-server |     return meth(obj, **kw)
saraki-server |   File "/opt/venv/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 783, in visit_metadata
saraki-server |     self.traverse_single(
saraki-server |   File "/opt/venv/lib/python3.8/site-packages/sqlalchemy/sql/visitors.py", line 145, in traverse_single
saraki-server |     return meth(obj, **kw)
saraki-server |   File "/opt/venv/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 827, in visit_table
saraki-server |     self.connection.execute(
saraki-server |   File "/opt/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
saraki-server |     return meth(self, multiparams, params)
saraki-server |   File "/opt/venv/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
saraki-server |     return connection._execute_ddl(self, multiparams, params)
saraki-server |   File "/opt/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1068, in _execute_ddl
saraki-server |     ret = self._execute_context(
saraki-server |   File "/opt/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
saraki-server |     self._handle_dbapi_exception(
saraki-server |   File "/opt/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
saraki-server |     util.raise_(
saraki-server |   File "/opt/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
saraki-server |     raise exception
saraki-server |   File "/opt/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
saraki-server |     self.dialect.do_execute(
saraki-server |   File "/opt/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
saraki-server |     cursor.execute(statement, parameters)
saraki-server |   File "/opt/venv/lib/python3.8/site-packages/mysql/connector/cursor.py", line 551, in execute
saraki-server |     self._handle_result(self._connection.cmd_query(stmt))
saraki-server |   File "/opt/venv/lib/python3.8/site-packages/mysql/connector/connection.py", line 490, in cmd_query
saraki-server |     result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
saraki-server |   File "/opt/venv/lib/python3.8/site-packages/mysql/connector/connection.py", line 395, in _handle_result
saraki-server |     raise errors.get_exception(packet)
saraki-server | sqlalchemy.exc.ProgrammingError: (mysql.connector.errors.ProgrammingError) 1067 (42000): Invalid default value for 'is_owner'
saraki-server | [SQL:
saraki-server | CREATE TABLE membership (
saraki-server | 	user_id INTEGER NOT NULL,
saraki-server | 	org_id INTEGER NOT NULL,
saraki-server | 	is_owner BOOL NOT NULL DEFAULT 'FALSE',
saraki-server | 	enabled BOOL NOT NULL,
saraki-server | 	PRIMARY KEY (user_id, org_id),
saraki-server | 	FOREIGN KEY(user_id) REFERENCES user (id),
saraki-server | 	FOREIGN KEY(org_id) REFERENCES org (id),
saraki-server | 	CHECK (is_owner IN (0, 1)),
saraki-server | 	CHECK (enabled IN (0, 1))
saraki-server | )
saraki-server |
saraki-server | ]
saraki-server | (Background on this error at: http://sqlalche.me/e/13/f405)
```

## Goal
My aim is to extend saraki and migrate components from https://github.com/StanGirard/seo-audits-toolkit in order to allow seo audits per organization/team layers.

## Questions
- Do you think it is worth to give a try to saraki for such purpose ? Either, do you know another flask/sqlalchemy framework for doing so ?
- Is it possible to support mysql with saraki ? Can you update the code ?
- Have you considered to create a front end to saraki ?

Thanks for any insights or inputs on these questions.

Cheers,
Luc Michalski

**Comment by mbarakaja** [comment]
Hello @lucmichalski 

I am about to leave now so I am away from my keyboard. But I'll be happy to answer all your questions tomorrow in detail.
Thank  you so much for your interest in this project.

**Comment by ghost** [comment]
Awesome :-)

**Comment by mbarakaja** [comment]
Hi again, is Sunday for me so I'll try my best to answer all the questions :)

- To start with, why does this project exist?

Many years ago I worked on a project where the requirement was to allow access to data related to a service to customers (usually companies). Those companies needed to give access to private data to their own customers.

It turned out that the customers were customers from multiple companies, so the same customer could access private data from multiples companies. 

This is similar to services like Github. You can create a user account, give access to other accounts, create organization accounts, and assign to the organization other accounts (members), etc.

One of the challenges was to make the authorization system pretty granular so that the organizations could set up the access level per user accounts without any hardcoded access level.

The final result was pretty good so I decided to make some parts of the project opensource.


- Is it possible to support MySQL with Saraki? Can you update the code?

The original project was build on top of PostgreSQL where I used[ schemas](https://www.postgresql.org/docs/9.1/ddl-schemas.html) to separate each tenant (organization accounts) to their namespace. There are good and bad things about schemas but for Saraki I decided to go with a more traditional approach using shared tables and FKs. I believe is easier to apply database sharding in that way.

I am aware that a serious project needs to support the major RDBMS vendors so I am willing to update the code at some point for sure :)

- Have you considered creating a front end for Saraki?

Yes. I was planning to create a separate project to build something similar to Django-admin for Flask + SQAlchemy, but with a completely different approach. I don't like the way Django pollutes the ORM layer making it glued to the admin. There isn't a separation of concern.

A front-end is necessary to make it easier to set up accounts and [authorization settings.](https://saraki.readthedocs.io/en/latest/auth.html)

This is a big topic though.

- About the exception in your post

Judging by the message it doesn't look like a feature issue (E.g. schemas do not exist in MySQL), but maybe something that needs to be set up or perhaps a bug that can be solved by upgrading SQLAlchemy. I'm not sure honestly right now.

---

> My aim is to extend saraki and migrate components from https://github.com/StanGirard/seo-audits-toolkit in order to allow seo audits per organization/team layers.

This is not clear to me. Do you want to move components from that project into Saraki? Or Do you want to use Saraki for that project?

> Do you think it is worth to give a try to saraki for such purpose ? Either, do you know another flask/sqlalchemy framework for doing so ?

Saraki is not production-ready. So is up to you. There is a lot of work to do and I won't be able to work on Saraki until January 11, 2021 :)

I don't know of any other similar project.

**Comment by ghost** [comment]
Hi,

Thanks for this detailed answer :-)

Do you have a Linkedin/Telegram/Twitter so I can DM you without polluting this thread ?

Telegram: "deepocrates"
Linkedin: https://www.linkedin.com/in/luc-m-2751909/
Twitter: https://twitter.com/lucmichalski

So I can give you more details about the integration.

Cheers,
Luc Michalski
